In [68]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np

In [52]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD
from keras.utils import to_categorical

In [3]:
data = load_breast_cancer()

In [5]:
X = data['data']

In [6]:
y = data['target']

In [7]:
X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [29]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size = 0.3, random_state=6)

In [30]:
pd.DataFrame(y).value_counts(normalize = True)

1    0.627417
0    0.372583
dtype: float64

In [31]:
pd.DataFrame(train_y).value_counts(normalize = True)

1    0.653266
0    0.346734
dtype: float64

In [32]:
pd.DataFrame(test_y).value_counts(normalize = True)

1    0.567251
0    0.432749
dtype: float64

In [36]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size = 0.3, random_state=234, stratify = y)

In [37]:
pd.DataFrame(train_y).value_counts(normalize = True)

1    0.628141
0    0.371859
dtype: float64

In [38]:
pd.DataFrame(test_y).value_counts(normalize = True)

1    0.625731
0    0.374269
dtype: float64

In [42]:
train_X.shape

(398, 30)

In [43]:
train_X.shape[1]

30

In [41]:
model = Sequential()

In [44]:
model.add(Dense(32, input_shape = (train_X.shape[1],), activation = 'sigmoid'))
model.add(Dense(16, activation = 'sigmoid'))
model.add(Dense(8, activation = 'sigmoid'))
model.add(Dense(4, activation = 'sigmoid'))
model.add(Dense(2, activation = 'sigmoid'))
model.add(Dense(1, activation = 'sigmoid'))

In [45]:
optim = SGD()
model.compile(optimizer = optim, loss = 'binary_crossentropy', metrics = ['accuracy'] )

In [46]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                992       
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 8)                 136       
                                                                 
 dense_3 (Dense)             (None, 4)                 36        
                                                                 
 dense_4 (Dense)             (None, 2)                 10        
                                                                 
 dense_5 (Dense)             (None, 1)                 3         
                                                                 
Total params: 1705 (6.66 KB)
Trainable params: 1705 (6.6

In [47]:
model.fit(train_X, train_y, epochs = 100, batch_size = 100, verbose = 2, validation_data= (test_X,test_y))

Epoch 1/100
4/4 - 6s - loss: 0.7704 - accuracy: 0.3719 - val_loss: 0.7672 - val_accuracy: 0.3743 - 6s/epoch - 2s/step
Epoch 2/100
4/4 - 0s - loss: 0.7669 - accuracy: 0.3719 - val_loss: 0.7638 - val_accuracy: 0.3743 - 79ms/epoch - 20ms/step
Epoch 3/100
4/4 - 0s - loss: 0.7636 - accuracy: 0.3719 - val_loss: 0.7606 - val_accuracy: 0.3743 - 64ms/epoch - 16ms/step
Epoch 4/100
4/4 - 0s - loss: 0.7603 - accuracy: 0.3719 - val_loss: 0.7575 - val_accuracy: 0.3743 - 80ms/epoch - 20ms/step
Epoch 5/100
4/4 - 0s - loss: 0.7572 - accuracy: 0.3719 - val_loss: 0.7544 - val_accuracy: 0.3743 - 77ms/epoch - 19ms/step
Epoch 6/100
4/4 - 0s - loss: 0.7542 - accuracy: 0.3719 - val_loss: 0.7515 - val_accuracy: 0.3743 - 65ms/epoch - 16ms/step
Epoch 7/100
4/4 - 0s - loss: 0.7513 - accuracy: 0.3719 - val_loss: 0.7487 - val_accuracy: 0.3743 - 75ms/epoch - 19ms/step
Epoch 8/100
4/4 - 0s - loss: 0.7484 - accuracy: 0.3719 - val_loss: 0.7459 - val_accuracy: 0.3743 - 83ms/epoch - 21ms/step
Epoch 9/100
4/4 - 0s - loss:

In [49]:
model.evaluate(train_X,train_y)

13/13 [==============================] - 0s 3ms/step - loss: 0.6654 - accuracy: 0.6281


[0.6653720140457153, 0.6281406879425049]

In [50]:
model.evaluate(test_X,test_y)

6/6 [==============================] - 0s 5ms/step - loss: 0.6661 - accuracy: 0.6257


[0.6661239862442017, 0.6257309913635254]

In [51]:
model.predict(test_X)

6/6 [==============================] - 0s 3ms/step


array([[0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.57676893],
       [0.5766836 ],
       [0.57676244],
       [0.576769  ],
       [0.576769  ],
       [0.5766837 ],
       [0.5766836 ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.5767366 ],
       [0.576769  ],
       [0.576769  ],
       [0.5766836 ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.5766084 ],
       [0.576769  ],
       [0.576769  ],
       [0.576769  ],
       [0.57676893],
       [0.576769  ],
       [0.5765993 ],
       [0.576769  ],
       [0.5766836 ],
       [0.5766836 ],
       [0.576769  ],
       [0.57686985],
       [0.576769  ],
       [0.576769  ],
       [0.5767684 ],
       [0.576

Using Softmax in output layer

In [55]:
y_cat = to_categorical(y)

In [58]:
train_X, test_X, train_y, test_y = train_test_split(X,y_cat, test_size = 0.3, random_state=6)

In [81]:
model = Sequential()

In [82]:
model.add(Dense(32, input_shape = (train_X.shape[1],), activation = 'sigmoid'))
model.add(Dense(16, activation = 'sigmoid'))
model.add(Dense(8, activation = 'sigmoid'))
model.add(Dense(4, activation = 'sigmoid'))
model.add(Dense(2, activation = 'sigmoid'))
model.add(Dense(2, activation = 'softmax'))

In [83]:
optim = SGD()
model.compile(optimizer = optim, loss = 'binary_crossentropy', metrics = ['accuracy'] )

In [84]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_24 (Dense)            (None, 32)                992       
                                                                 
 dense_25 (Dense)            (None, 16)                528       
                                                                 
 dense_26 (Dense)            (None, 8)                 136       
                                                                 
 dense_27 (Dense)            (None, 4)                 36        
                                                                 
 dense_28 (Dense)            (None, 2)                 10        
                                                                 
 dense_29 (Dense)            (None, 2)                 6         
                                                                 
Total params: 1708 (6.67 KB)
Trainable params: 1708 (6

In [85]:
model.fit(train_X, train_y, epochs = 100, batch_size = 100, verbose = 2, validation_data= (test_X,test_y))

Epoch 1/100
4/4 - 1s - loss: 0.7818 - accuracy: 0.3467 - val_loss: 0.7453 - val_accuracy: 0.4327 - 1s/epoch - 273ms/step
Epoch 2/100
4/4 - 0s - loss: 0.7793 - accuracy: 0.3467 - val_loss: 0.7437 - val_accuracy: 0.4327 - 59ms/epoch - 15ms/step
Epoch 3/100
4/4 - 0s - loss: 0.7768 - accuracy: 0.3467 - val_loss: 0.7421 - val_accuracy: 0.4327 - 41ms/epoch - 10ms/step
Epoch 4/100
4/4 - 0s - loss: 0.7744 - accuracy: 0.3467 - val_loss: 0.7405 - val_accuracy: 0.4327 - 57ms/epoch - 14ms/step
Epoch 5/100
4/4 - 0s - loss: 0.7720 - accuracy: 0.3467 - val_loss: 0.7390 - val_accuracy: 0.4327 - 62ms/epoch - 15ms/step
Epoch 6/100
4/4 - 0s - loss: 0.7696 - accuracy: 0.3467 - val_loss: 0.7375 - val_accuracy: 0.4327 - 41ms/epoch - 10ms/step
Epoch 7/100
4/4 - 0s - loss: 0.7674 - accuracy: 0.3467 - val_loss: 0.7360 - val_accuracy: 0.4327 - 57ms/epoch - 14ms/step
Epoch 8/100
4/4 - 0s - loss: 0.7651 - accuracy: 0.3467 - val_loss: 0.7345 - val_accuracy: 0.4327 - 81ms/epoch - 20ms/step
Epoch 9/100
4/4 - 0s - lo

In [86]:
model.evaluate(train_X,train_y)

13/13 [==============================] - 0s 3ms/step - loss: 0.6681 - accuracy: 0.6533


[0.6681183576583862, 0.6532663106918335]

In [87]:
model.evaluate(test_X,test_y)

6/6 [==============================] - 0s 4ms/step - loss: 0.6861 - accuracy: 0.5673


[0.6860703825950623, 0.567251443862915]

In [88]:
model.predict(test_X)

6/6 [==============================] - 0s 2ms/step


array([[0.39719516, 0.60280484],
       [0.39720383, 0.6027962 ],
       [0.39700028, 0.60299975],
       [0.39736298, 0.60263705],
       [0.39761442, 0.6023856 ],
       [0.39734462, 0.6026554 ],
       [0.39701682, 0.6029832 ],
       [0.39761442, 0.6023856 ],
       [0.3969872 , 0.60301286],
       [0.39698976, 0.60301024],
       [0.3969864 , 0.60301363],
       [0.39699176, 0.6030082 ],
       [0.39732558, 0.6026744 ],
       [0.39699712, 0.60300285],
       [0.39761442, 0.6023856 ],
       [0.39758906, 0.602411  ],
       [0.39761442, 0.6023856 ],
       [0.39719516, 0.60280484],
       [0.3971597 , 0.60284024],
       [0.39761442, 0.6023856 ],
       [0.39736336, 0.60263664],
       [0.39701894, 0.6029811 ],
       [0.3976137 , 0.6023863 ],
       [0.3972697 , 0.6027303 ],
       [0.39719516, 0.60280484],
       [0.39735427, 0.60264575],
       [0.39700454, 0.60299546],
       [0.39719516, 0.60280484],
       [0.39719537, 0.60280466],
       [0.39719516, 0.60280484],
       [0.

In [89]:
np.argmax(model.predict(test_X), axis = 1)

6/6 [==============================] - 0s 2ms/step


array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [90]:
np.argmax(np.array([6,2,4]))

0