In [1]:
from preprocessing import preprocess, load_objects
import joblib
import numpy as np

In [2]:
model = joblib.load('model.pkl')

In [3]:
model

LinearRegression()

In [4]:
model.intercept_

662076.4124605337

In [5]:
model.coef_

array([ -92983.60392997, -289573.63363582,  382557.23756578,
         15437.16893038,  -15437.16893038, -295437.22545287])

In [6]:
imputer = joblib.load('impute.pkl')

In [7]:
encode = joblib.load('encode.pkl')

In [8]:
scale = joblib.load('scale.pkl')

In [9]:
new_test = ['maruti','petrol',np.NaN]

In [12]:
model.predict(preprocess(new_test, imputer, encode, scale))

array([232361.1974338])

In [13]:
new_test = ['maruti','diesel',np.NaN]
model.predict(preprocess(new_test, imputer, encode, scale))

array([263235.53529457])

In [3]:
model, imputer, encode, scale = load_objects()

In [4]:
new_test = ['maruti','diesel',np.NaN]
model.predict(preprocess(new_test, imputer, encode, scale))

array([263235.53529457])