In [2]:
# model = Equation (coeff, intercept)

In [ ]:
# save model
# portable ship
# load model
# predict

In [ ]:
train 
test

Hackathon
train+test -> Preprocessing (Hackathon)

train - flight price - carrier - indigo, airindia, jet

testflight price - carrier - indigo, airindia, jet, vistara


combined and onehot -> no problem in forseen

missing value -> imputation -> mean -> train+test


Realworld
Train - Preprocessing



Test - We don't have - Preprocess -> predict


Extra Burden on the devepoler to repeat the step of preprocessing 

Ship the processing code with the model



train - flight price - carrier - indigo, airindia, jet

test - flight price - carrier - indigo, airindia, jet, vistara


separatly did the onehot -> problem 


missing value -> imputation -> mean -> train



In [144]:
import pandas as pd
import numpy as np

from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import MinMaxScaler


from sklearn.linear_model import LinearRegression

In [158]:
data = pd.DataFrame(
{
    'name':['maruti','honda','maruti','toyota','honda','toyota'],
    'fuel_type':['petrol','diesel','petrol','diesel','petrol','diesel'],
    'km_driven' :[2000,4000,100,6344,1234,np.NaN],
    'price' :[200000,400000,424232,800000,500000,900000]
    
}
)
 

In [159]:
data

name fuel_type  km_driven   price
0  maruti    petrol     2000.0  200000
1   honda    diesel     4000.0  400000
2  maruti    petrol      100.0  424232
3  toyota    diesel     6344.0  800000
4   honda    petrol     1234.0  500000
5  toyota    diesel        NaN  900000

In [160]:
impute = SimpleImputer()
imputed_data = impute.fit_transform(data[['km_driven']])

In [161]:
data['km_driven'] = imputed_data

In [163]:
data

name fuel_type  km_driven   price
0  maruti    petrol     2000.0  200000
1   honda    diesel     4000.0  400000
2  maruti    petrol      100.0  424232
3  toyota    diesel     6344.0  800000
4   honda    petrol     1234.0  500000
5  toyota    diesel     2735.6  900000

In [164]:
data

name fuel_type  km_driven   price
0  maruti    petrol     2000.0  200000
1   honda    diesel     4000.0  400000
2  maruti    petrol      100.0  424232
3  toyota    diesel     6344.0  800000
4   honda    petrol     1234.0  500000
5  toyota    diesel     2735.6  900000

In [165]:
encode = OneHotEncoder(sparse = False,handle_unknown='ignore')

In [166]:
encoded_data = encode.fit_transform(data[['name','fuel_type']])

In [167]:
encoded_data

array([[0., 1., 0., 0., 1.],
       [1., 0., 0., 1., 0.],
       [0., 1., 0., 0., 1.],
       [0., 0., 1., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 1., 1., 0.]])

In [168]:
type(encoded_data)

numpy.ndarray

In [199]:
encode.get_feature_names_out()


array(['name_honda', 'name_maruti', 'name_toyota', 'fuel_type_diesel',
       'fuel_type_petrol'], dtype=object)

In [170]:
scale = MinMaxScaler()

In [171]:
scaled_data = scale.fit_transform(data[['km_driven']])

In [172]:
type(scaled_data)

numpy.ndarray

In [173]:
data_sclaled = np.concatenate([encoded_data,scaled_data], axis = 1)

In [174]:
column_name = encode.get_feature_names_out()

In [175]:
[list(column_name),'km_driven']

[['name_honda',
  'name_maruti',
  'name_toyota',
  'fuel_type_diesel',
  'fuel_type_petrol'],
 'km_driven']

In [176]:
column_name = list(column_name)

In [177]:
column_name.append('km_driven')

In [178]:
column_name

['name_honda',
 'name_maruti',
 'name_toyota',
 'fuel_type_diesel',
 'fuel_type_petrol',
 'km_driven']

In [179]:
X = pd.DataFrame(data_sclaled, columns=column_name)

In [180]:
y = data['price']

In [181]:
model = LinearRegression()
model.fit(X,y)

LinearRegression()

In [189]:
new_test = ['toyota','petrol',np.NaN]

In [190]:
new_ = pd.DataFrame(new_test).T

In [191]:
new_.columns = ['name','fuel_type', 'km_driven']

In [192]:
new_

name fuel_type km_driven
0  toyota    petrol       NaN

In [194]:
new_['km_driven'] = impute.transform(new_[['km_driven']])

In [195]:
new_

name fuel_type  km_driven
0  toyota    petrol     2735.6

In [205]:
res_encode_cat = encode.transform(new_[['name','fuel_type']])

In [202]:
new_['km_driven'] = scale.transform(new_[['km_driven']])

In [204]:
new_

name fuel_type  km_driven
0  toyota    petrol   0.422101

In [208]:
cat_out = pd.DataFrame(res_encode_cat, columns=encode.get_feature_names_out())

In [211]:
final_preprocessed = pd.concat([cat_out,new_['km_driven']],axis =1)

In [212]:
model.predict(final_preprocessed)

array([904492.0686354])

In [213]:
def preprocess(data):
    new_ = pd.DataFrame(data).T
    new_.columns = ['name','fuel_type', 'km_driven']
    new_['km_driven'] = impute.transform(new_[['km_driven']])
    res_encode_cat = encode.transform(new_[['name','fuel_type']])
    new_['km_driven'] = scale.transform(new_[['km_driven']])
    cat_out = pd.DataFrame(res_encode_cat, columns=encode.get_feature_names_out())
    final_preprocessed = pd.concat([cat_out,new_['km_driven']],axis =1)
    return final_preprocessed

In [216]:
new_test = ['honda','diesel',np.NaN]
preprocess(new_test)

name_honda  name_maruti  name_toyota  fuel_type_diesel  fuel_type_petrol  \
0         1.0          0.0          0.0               1.0               0.0   

   km_driven  
0   0.422101

In [218]:
new_test = ['honda','diesel',6557]
model.predict(preprocess(new_test))

array([279014.57631599])

In [219]:
# Save our Model

In [ ]:
# Pickle

In [220]:
import joblib

In [221]:
joblib.dump(model, 'model.pkl')

['model.pkl']

In [222]:
joblib.dump(impute, 'impute.pkl')


['impute.pkl']

In [223]:
joblib.dump(encode, 'encode.pkl')


['encode.pkl']

In [224]:
joblib.dump(scale, 'scale.pkl')


['scale.pkl']

In [227]:
import sklearn

In [229]:
sklearn.__version__

'1.0.2'